apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubelet-auth-daemonset.fullname" . | quote }}
  annotations: {{ .Values.annotations | toJson }}
  labels:
{{ include "kubelet-auth-daemonset.labels" . | indent 4 }}
data:
  write_docker_config.py: |
{{ .Files.Get "files/write_docker_config.py" | indent 4 }}
