apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kubelet-auth-daemonset.fullname" . | quote }}
  annotations: {{ .Values.annotations | toJson }}
  labels:
{{ include "kubelet-auth-daemonset.labels" . | indent 4 }}
spec:
  backendType: secretsManager
  roleArn: {{ required "Must specify a role ARN for external-secrets to assume" .Values.externalSecretsRoleArn | quote }}
  dataFrom:
    - {{ required "Must specify a secret ARN for the registry credentials" .Values.registryCredentialSecretArn | quote }}
